import {
  Bell,
  BookOpen,
  Box,
  BracketsAngle,
  CloudSun,
  Heart,
  Home,
  Mail,
  Menu,
  Moon,
  ColorsSwatch,
  Search,
  Settings2,
  User,
} from "pixelarticons/react"

export const commonIcons = [
  { label: "home", Icon: Home },
  { label: "docs", Icon: BookOpen },
  { label: "component", Icon: Box },
  { label: "tokens", Icon: ColorsSwatch },
  { label: "code", Icon: BracketsAngle },
  { label: "search", Icon: Search },
  { label: "mail", Icon: Mail },
  { label: "bell", Icon: Bell },
  { label: "user", Icon: User },
  { label: "settings", Icon: Settings2 },
  { label: "menu", Icon: Menu },
  { label: "moon", Icon: Moon },
  { label: "sun", Icon: CloudSun },
  { label: "heart", Icon: Heart },
]
